name: stac
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal
  - geopandas
  - dask
  - jupyterlab
  - pyproj
  - pystac-client
  - pystac  
  - requests  
  - rioxarray
  - stackstac
  - libgdal-jp2openjpeg
  - python-graphviz
  - jupyter-resource-usage
  - dask-labextension
