model_name: PredictSpruceForestsModel
model_path: ''

train: true
infer: false

pretrained: false
nn_framework: torch
batch_size: 12

data_specs:
  width: 650
  height: 650
  dtype:
  image_type: normalized
  rescale: false
  rescale_minima: auto
  rescale_maxima: auto
  channels: 3
  label_type: mask
  is_categorical: false
  mask_channels: 1
  val_holdout_frac: 0.2
  data_workers: 1

training_data_csv: 'tile_filepaths_for_training.csv'
validation_data_csv:
inference_data_csv:

training_augmentation:
  augmentations:
    HorizontalFlip:
      p: 0.5
    RandomRotate90:
      p: 0.5
    RandomCrop:
      height: 512
      width: 512
      p: 1.0
    Normalize:
      mean:
        - 0.17395850358514
        - 0.035442982050778
        - 0.041676467416446
      std:
        - 0.10218734901152
        - 0.029166612631494
        - 0.02251037551648
      max_pixel_value: 1.0
      p: 1.0
  p: 1.0
  shuffle: true
validation_augmentation:
  augmentations:
    CenterCrop:
      height: 512
      width: 512
      p: 1.0
    Normalize:
      mean:
        - 0.17395850358514
        - 0.035442982050778
        - 0.041676467416446
      std:
        - 0.10218734901152
        - 0.029166612631494
        - 0.02251037551648
      max_pixel_value: 1.0
      p: 1.0
  p: 1.0
inference_augmentation:
  augmentations:
    Normalize:
      mean:
        - 0.17396631162454
        - 0.033582232626573
        - 0.040423970924474
      std:
        - 0.093608074909319
        - 0.027442049122189
        - 0.022834374265174
      max_pixel_value: 1.0
      p: 1.0
  p: 1.0
training:
  epochs: 30
  steps_per_epoch:
  optimizer: Adam
  lr: 1e-3
  opt_args:
  loss:
    bcewithlogits:
    jaccard:
  loss_weights:
    bcewithlogits: 10
    jaccard: 2.5
  metrics:
    training:
    validation:
  checkpoint_frequency: 100
  callbacks:
    model_checkpoint:
      filepath: ''
      monitor: val_loss
  model_dest_path: 'PredictSpruceForestsModel_final.pth'
  verbose: true
