name: base
channels:
    - conda-forge
dependencies:
    - python
    - geopandas
    - rasterio
    - scikit-learn
    - imbalanced-learn
    - descartes 
    - matplotlib 
    - jupyterlab 
    - rasterio
    - scikit-learn 
    - imbalanced-learn 
    - rclone