---

- name: Deploy VM
  hosts: localhost
  collections:
    - openstack.cloud
  vars:
    installed_packages: "opendronemap"

  roles:
    - openstack

- name: Install Docker and OpenDroneMap
  hosts: created_instances
  gather_facts: false
  collections:
    - openstack.cloud

  roles:
    - docker
    - opendronemap