---

- name: Deploy VM
  hosts: localhost
  collections:
    - openstack.cloud
  vars:
    installed_packages: "postgis"

  roles:
    - openstack

- name: Install Docker and PostGIS
  hosts: created_instances
  gather_facts: false
  collections:
    - openstack.cloud
  vars:
    postgis_version: "16-3.4" # If you want to install a different version of GeoServer, change this variable

  roles:
    - docker
    - postgis
