---

- name: Deploy VM
  hosts: localhost
  collections:
    - openstack.cloud
  vars:
    installed_packages: "geoserver"
    
  roles:
    - openstack

- name: Install Docker and GeoServer
  hosts: created_instances
  collections:
    - openstack.cloud
  vars:
    geoserver_version: "2.25.2" # If you want to install a different version of GeoServer, change this
    geoserver_datadir: "/geoserver_data"

  roles:
    - docker
    - geoserver
